Repository marsamber/Acme-Toolkits, pull requests merged in 2022-05, with the labels that each got.

#184 Task-067: updated
  src/main/java/acme/features/inventor/item/InventorItemRepository.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitCreateService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitDeleteService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitPublishService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitUpdateService.java
  src/main/java/acme/features/inventor/toolkitItem/InventorToolkitItemCreateService.java
  src/main/java/acme/features/inventor/toolkitItem/InventorToolkitItemUpdateService.java
  src/main/webapp/WEB-INF/resources/sample-data/toolkit_item.csv
  src/main/webapp/WEB-INF/views/any/toolkit/form.jsp
  src/main/webapp/WEB-INF/views/any/toolkit/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/toolkit/messages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit-item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit-item/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit-item/messages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit/messages-es.i18n
  src/test/java/acme/testing/any/toolkit/AnyToolkitListByItemTest.java
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitListAllTest.java
  src/test/resources/any/toolkit/list-by-item.csv
  src/test/resources/inventor/toolkit/list-all.csv
Labels: enhancement

#185 Task 063: done
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorController.java
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorCreateService.java
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorRepository.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronController.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronCreateService.java
  src/main/resources/banner.txt
  src/main/webapp/WEB-INF/views/authenticated/inventor/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/inventor/messages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/inventor/messages-es.i18n
  src/main/webapp/WEB-INF/views/authenticated/patron/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/patron/messages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/patron/messages-es.i18n
Labels: enhancement

#187 Tasl 080.1: done
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitCreateTest.java
  src/test/resources/inventor/toolkit/create-negative.csv
  src/test/resources/inventor/toolkit/create-positive.csv
Labels: test

#190 Task 065 : done
  src/main/java/acme/features/inventor/item/InventorItemDeleteService.java
  src/main/java/acme/features/inventor/item/InventorItemRepository.java
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
Labels: help wanted

#191 Task 80.3: done
  src/main/webapp/WEB-INF/resources/sample-data/announcement.csv
  src/test/java/acme/testing/antiSpam/AntiSpamTest.java
  src/test/java/acme/testing/authenticated/announcement/AnnouncementRepository.java
  src/test/java/acme/testing/authenticated/announcement/RecentAnnouncementListTest.java
  src/test/resources/authenticated/announcement/list-recent.csv
  src/test/resources/inventor/item/negative-spam.csv
Labels: test

#194 Task 080.4: Test suite : done
  src/main/java/acme/features/inventor/item/InventorItemPublishedService.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/test/java/acme/testing/inventor/item/IventorItemByComponentTest.java
  src/test/java/acme/testing/inventor/item/IventorItemByToolTest.java
  src/test/resources/inventor/item/create-tool.csv
  src/test/resources/inventor/item/deleteComponent.csv
  src/test/resources/inventor/item/negative-create-tool.csv
  src/test/resources/inventor/item/negativeDeleteComponent.csv
Labels: test

#198 Task 080.1: update
  src/test/java/acme/testing/any/toolkit/AnyToolkitListByItemTest.java
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitListAllTest.java
  src/test/resources/any/toolkit/list-all.csv
  src/test/resources/any/toolkit/list-by-item.csv
  src/test/resources/inventor/toolkit/create-negative.csv
  src/test/resources/inventor/toolkit/create-positive.csv
  src/test/resources/inventor/toolkit/list-all.csv
Labels: bug

#200 Task-067: update
  src/main/java/acme/features/inventor/toolkitItem/InventorToolkitItemCreateService.java
Labels: bug
